CREATE TABLE maintenance_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    maintenance_date DATE NOT NULL,
    mileage INT,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    vehicle_id INT REFERENCES vehicles(id)
);