CREATE TABLE IF NOT EXISTS vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_plate VARCHAR(20) UNIQUE NOT NULL,
    model VARCHAR(50) NOT NULL,
    manufacturer VARCHAR(50) NOT NULL,
    production_year INT DEFAULT 1900 NOT NULL,
    fuel_capacity DECIMAL(5, 2),
    average_consumption DECIMAL(5, 2) DEFAULT 0 NOT NULL,
    mileage INT DEFAULT 0 NOT NULL,
    route_records INT DEFAULT 0 NOT NULL,
    last_maintenance DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL
);